activation: leaky_relu
architecture: fully_connected
"decoder_\u03B1_offset": 0.0001
eps: 1.0e-07
input_dims: !!python/tuple
- 1
- 28
- 28
latent_dims:
- 10
learning_rate: 0.001
n_mc_samples: 3
ood_z_generation_method: gd_aggregate_posterior
prior_b: null
prior_epistemic_c: null
prior_extrapolation_mode: null
prior_extrapolation_x: null
"\u03C4_ood": 0.5
