activation: leaky_relu
architecture: convolutional
"decoder_\u03B1_offset": 0.001
eps: 0.001
input_dims: !!python/tuple
- 3
- 32
- 32
latent_dims: !!python/tuple
- 128
learning_rate: 0.001
n_mc_samples: 1
ood_z_generation_method: null
prior_b: null
prior_epistemic_c: null
prior_extrapolation_mode: null
prior_extrapolation_x: null
"\u03C4_ood": 0
